require:
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec
  - rubocop-packaging
  - rubocop-performance

AllCops:
  NewCops: enable

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false